services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/src
    ports:
      - "8083:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "8080"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      TZ: "Asia/Ho_Chi_Minh"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=DoAnServerNangCao;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      Minio__Endpoint: "minio:9000"
      Minio__AccessKey: "admin"
      Minio__SecretKey: "admin123"
      Minio__BucketName: "football-field-booking-media"
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # container_name: sqlserver-do-an-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      TZ: "Asia/Ho_Chi_Minh"
    volumes:
      - sqlserver_data:/var/opt/mssql

  minio:
    image: minio/minio
    # container_name: minio-do-an-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - D:/MinIO/minio-data-do-an-server:/data
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:latest
    # container_name: nginx-do-an-server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  sqlserver_data:
