services:
  api:
    image: localhost:5000/football-api:latest
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=DoAnServerNangCao;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      Minio__Endpoint: "minio:9000"
      Minio__AccessKey: "admin"
      Minio__SecretKey: "admin123"
      Minio__BucketName: "sanbong"
    depends_on:
      - db
      - minio

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - D:/MinIO/minio-data-do-an-server:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  sqlserver_data:
